#!/bin/bash
# the code below will search html and javascript
#find -not -path "*/benchmarks/*" -not -path "./cpan/*" -and -not -path "./quale/cpan/*" -and -not -path "./tmp/*" -and -not -path "*/dojo-release/*" -and -not -name "dojo.js" -and \( -name "*.pm" -or -name "*.tt" -or -name "*.pl" -or -name "*.t" -or -name "*.html" -or -name "*.js" \) | xargs grep -n -i "$1"

if [ $# = 1 ]; then
  ROOT_OF_SEARCH="./"
  QUERY=$1
fi

if [ $# = 2 ]; then
  ROOT_OF_SEARCH="${ROOT_OF_SEARCH}$1"
  QUERY=$2
fi

find $ROOT_OF_SEARCH -not -path "*/build/*" -and -not -path "*/migrations/*" -and -not -path "*/javascripts/*" -and -not -path "*node_modules/*" -and \( -name "*.py" -or -name "*.html" -or -name "*.js" -or -name "*.jst" -or -name "*.scss" -or -name "*.coffee" -or -name "*.pp" -or -name "*.go" \) | xargs grep --color -n -i "$QUERY"

# find \
#     $ROOT_OF_SEARCH \
#  -not -path "./tmp/*" \
#  -and \
#    \( -name "*.pm" \
#       -or -name "*.tt" \
#       -or -name "*.pl" \
#       -or -name "*.t" \
#       -or -name "*.yml" \
#       -or -name "*.pp" \) \
# | xargs grep --color -n -i "$QUERY"

